version: 2.1

defaults:
  workspace_root: &workspace_root
    ~/next-runtime-dotenv

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: cimg/node:lts

  filters: &default_filters
    tags:
      only: '/v[0-9]+(\.[0-9]+)*/'

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  restore-nodejs:
    description: "Restore Node.js dependencies"
    parameters:
      key:
        type: string
      working_directory:
        type: string
        default: *workspace_root
      default_branch:
        type: string
        default: master
    steps:
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - << parameters.key >>-nodejs-{{ .Branch }}-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
            - << parameters.key >>-nodejs-<< parameters.default_branch >>-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
            - << parameters.key >>-nodejs-<< parameters.default_branch >>-

  install-nodejs:
    description: "Install Node.js dependencies"
    parameters:
      key:
        type: string
      working_directory:
        type: string
        default: *workspace_root
    steps:
      - restore-nodejs:
          key: << parameters.key >>
          working_directory: << parameters.working_directory >>

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --non-interactive
          working_directory: << parameters.working_directory >>

      - save_cache:
          name: Save node_modules cache
          key: << parameters.key >>-nodejs-{{ .Branch }}-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
          paths:
            - << parameters.working_directory >>/node_modules

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace

      - install-nodejs:
          key: v1-next-runtime-dotenv

  lint:
    <<: *nodejs_container
    steps:
      - *attach_workspace

      - restore-nodejs:
          key: v1-next-runtime-dotenv

      - run:
          name: Lint JavaScript
          command: yarn xo

  test:
    <<: *nodejs_container
    steps:
      - *attach_workspace

      - restore-nodejs:
          key: v1-next-runtime-dotenv

      - run:
          name: Run tests
          command: yarn test --ci

      - store_test_results:
          path: reports/tests/

      - run:
          name: Upload code coverage to codecov
          command: yarn codecov

workflows:
  version: 2

  push:
    jobs:
      - checkout:
          filters: *default_filters

      - install:
          requires:
            - checkout
          filters: *default_filters

      - lint:
          requires:
            - install
          filters: *default_filters

      - test:
          requires:
            - install
          filters: *default_filters
